### ISSUE TITLE
line 47

### ISSUE THREAD

**Issue by alfnitacoder** [sripirakas/GoogleSearch#1]
Start: 0
Traceback (most recent call last):
  File "google.py", line 2, in <module>
    response = GoogleSearch().search("something")
  File "C:\Users\ageorge\PycharmProjects\google\venv\lib\site-packages\googlesearch\googlesearch.py", line 47, in search
    totalText = soup.select(GoogleSearch.TOTAL_SELECTOR)[0].children.__next__().encode('utf-8').decode('utf-8')
IndexError: list index out of range

**Comment by alfnitacoder** [comment]
line 47
 totalText = soup.select(GoogleSearch.TOTAL_SELECTOR)[0].children.__next__().encode('utf-8').decode('utf-8')

**Comment by 7eacemaker** [comment]
totalText = soup.select(GoogleSearch.TOTAL_SELECTOR)[0].children.__next__().encode('utf-8').decode('utf-8')
IndexError: list index out of range
